apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-challenge
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: code-challenge-container
          image: test1app:challenge-tag
          ports:
            - containerPort: 5000
